#!/bin/bash

java -Xms256M -Xmx512M -verbose:gc -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:+CMSIncrementalPacing -XX:CMSIncrementalDutyCycleMin=0 -XX:CMSIncrementalDutyCycle=10 -jar output-jars/InC_current.jar
