/* Generated By:JavaCC: Do not edit this line. MRAParserConstants.java */
package com.moseph.mra.parser;

public interface MRAParserConstants {

  int EOF = 0;
  int OPEN = 7;
  int CLOSE = 8;
  int ATT_SEP = 9;
  int OPEN_EXPR = 10;
  int CLOSE_EXPR = 11;
  int COMMA = 12;
  int CONNECTIVE = 13;
  int NEGATION = 14;
  int AND = 15;
  int OR = 16;
  int NUMBER = 17;
  int LETTER = 18;
  int DIGIT = 19;
  int NAMECHAR = 20;
  int NAME = 21;
  int PIECE_OPEN = 22;
  int SECTION_OPEN = 23;
  int ACTION_OPEN = 24;
  int BEHAVIOUR_OPEN = 25;
  int ACTIVEBEHAVIOUR_OPEN = 26;
  int DECISION_OPEN = 27;
  int CHANNEL_HEAD = 28;
  int QUOTEDSTR = 29;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"(\"",
    "\")\"",
    "\":\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "<CONNECTIVE>",
    "<NEGATION>",
    "<AND>",
    "<OR>",
    "<NUMBER>",
    "<LETTER>",
    "<DIGIT>",
    "<NAMECHAR>",
    "<NAME>",
    "<PIECE_OPEN>",
    "<SECTION_OPEN>",
    "<ACTION_OPEN>",
    "<BEHAVIOUR_OPEN>",
    "<ACTIVEBEHAVIOUR_OPEN>",
    "<DECISION_OPEN>",
    "<CHANNEL_HEAD>",
    "<QUOTEDSTR>",
  };

}
